### ISSUE TITLE
请问如何制作synthv字典？

### ISSUE THREAD

**Issue by johe123qwe** [Slidingwall/synthv-dictionaries#2]
我是一名音乐爱好者，因为 synthv 仅支持有限的语种，我想制作印尼语的字典，请问有没有制作字典的教程？谢谢！

**Comment by Slidingwall** [comment]
嗨，你好！这是一个非常好的问题！
制作其他语言的字典，需要确定这个语言所包含的元音以及辅音都有哪些。你可以从维基百科上面找到相关的资料。
然后，你需要确定这些元音或辅音是否包含在已知的中文、英语或者日语的音素中。好消息是，大部分的语言所用到的元音辅音基本都是重叠的！但是，有些元音或者辅音可能无法找到准确的替代。你可以用Excel表格来记录这些元音与辅音在中文、英语、日语中分别可以用什么替代。
接着，你需要找出这门语言中的所有音节，并将它们用音素表示。如果这门语言像中文、日语、韩语这样，每个音节都可以用**固定的字符**表示，那么你的工作会轻松很多。你可以先用这门语言的拼读方式将音素分开（例如汉语拼音、罗马字、韩语转写等等），再将它们转换为Synthesizer V支持的音素。
你会得到像这样的数据：
|原始语言|拆分的音素|
|:---:|:---:|
|ba|b a|
|be|b e|
|...|...|

接下来是处理已经得到的数据，Excel还是非常好用的工具！它可以快速的完成复制、粘贴、填充、分列、替换等工作，也可以用一些公式，例如`=A1&" "&B1`等，将替换后的音素合并到同一个单元格内。复制它们并选择“粘贴为文本”，以得到不带公式填充的内容。
接下来，假设你已经获得了像这样的数据：
|原始语言|目标语言|
|:---:|:---:|
|ba|b a|
|be|b e|
|...|...|

Synthesizer V的字典是层层嵌套的JSON数组。它核心部分的格式类似这样：
```json
    {
      "w": "ba",
      "p": "b a"
    },
    {
      "w": "be",
      "p": "b e"
    },
```
因此，为了方便转换，你可以在表格前后插入列：
||原始语言||目标语言||
|:---:|:---:|:---:|:---:|:---:|
|{"w":"|ba|","p":"|b a|"},|
|{"w":"|be|","p":"|b e|"},|
|...|...|...|...|...|

然后，打开文本编辑器或代码编辑器，将整个表格粘贴进其中。你可能需要用到查找与替换功能，将多余的空格和制表符删除，保证引号内的文本前后没有任何空格，而不是`" b a "`这样。
```json
{
  "data": [
    //在方括号中间粘贴所有的字典，同时记得删除右方括号前的最后一个逗号
  ]
}
```
将整个文件另存为`.json`，就可以导入进Synthesizer V来测试发音了！记得保存Excel文件和原始拆分的音素，以便后续进行修订。
此外，在[这里](https://synthv.info/resource-dicts#dicts/2.2)还有其他用户为其他语言制作的字典，例如法语、意大利语等。希望对你能起到一些帮助！

此外，如果这门语言中有丰富的双元音（例如英语中的`ay``ey``oy``aw``ow`，汉语中的`ia``ie``AU``@U`等），您也可以考虑在字典制作好后，用这些语言自带的双元音替换原有的单元音，以改善合成效果。一般来说，在代码编辑器（如VSCode）中操作这一步的效率最高。

**Comment by johe123qwe** [comment]
谢谢你耐心回答！这会我很有帮助！
